In [3]:


# Data Loading
import pandas as pd

df = pd.read_excel("healthcare_fraud_detection.xlsx")

# Data Profiling

In [15]:
df.head()

,Provider_ID,Claim_ID,Patient_Age,Patient_Gender,Diagnosis_Code,Procedure_Code,Claim_Amount,Approved_Amount,Insurance_Type,Claim_Submission_Date,Days_Between_Service_and_Claim,Number_of_Claims_Per_Provider_Monthly,Provider_Specialty,Patient_State,Claim_Status,Is_Fraud,Length_of_Stay,Visit_Type,Chronic_Condition_Flag,Prior_Visits_12m
0,P0052,C0000000,37,Male,I25.10,36415,443.51,393.16,Medicaid,2024-09-01,13,70,Cardiology,NY,Approved,0,0,Outpatient,1,2.0
1,P0121,C0000001,21,Female,E11.9,99213,467.50,461.33,Self-Pay,2022-09-05,5,62,General Practice,IL,Pending,0,5,Inpatient,1,2.0
2,P0140,C0000002,78,Female,J06.9,93000,591.69,530.06,Medicaid,2022-04-11,29,60,Cardiology,IL,Pending,0,5,Inpatient,1,3.0
3,P0202,C0000003,65,Male,I10,93000,235.15,189.11,Private,2023-10-11,22,70,General Practice,TX,Approved,0,0,Emergency,0,5.0
4,P0135,C0000004,36,Male,M54.5,85025,487.96,369.91,Private,2023-09-05,21,67,Pulmonology,PA,Approved,0,5,Inpatient,0,4.0

In [14]:
df.tail()

,Provider_ID,Claim_ID,Patient_Age,Patient_Gender,Diagnosis_Code,Procedure_Code,Claim_Amount,Approved_Amount,Insurance_Type,Claim_Submission_Date,Days_Between_Service_and_Claim,Number_of_Claims_Per_Provider_Monthly,Provider_Specialty,Patient_State,Claim_Status,Is_Fraud,Length_of_Stay,Visit_Type,Chronic_Condition_Flag,Prior_Visits_12m
9995,P0289,C0009995,79,Male,E78.5,71046,590.19,205.00,Private,2024-09-24,2,115,Internal Medicine,PA,Approved,1,2,Inpatient,1,3.0
9996,P0248,C0009996,66,Male,K21.9,93000,219.73,191.89,Self-Pay,2023-01-04,6,73,Orthopedics,IL,Approved,0,5,Inpatient,0,6.0
9997,P0122,C0009997,43,Female,F41.9,99213,505.24,447.94,Medicare,2024-06-30,6,59,Neurology,OH,Rejected,0,5,Emergency,1,0.0
9998,P0072,C0009998,39,Female,I10,93000,564.25,507.18,Medicare,2022-03-15,8,55,Cardiology,TX,Pending,0,5,Emergency,0,6.0
9999,P0137,C0009999,26,Male,J18.9,71046,564.52,563.74,Medicaid,2023-01-24,2,86,Neurology,CA,Approved,0,3,Outpatient,0,NaN

In [5]:
df.shape

(10000, 20)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Provider_ID                            10000 non-null  object
 1   Claim_ID                               10000 non-null  object
 2   Patient_Age                            10000 non-null  int64
 3   Patient_Gender                         10000 non-null  object
 4   Diagnosis_Code                         10000 non-null  object
 5   Procedure_Code                         10000 non-null  int64
 6   Claim_Amount                           10000 non-null  float64
 7   Approved_Amount                        10000 non-null  float64
 8   Insurance_Type                         9650 non-null   object
 9   Claim_Submission_Date                  10000 non-null  datetime64[ns]
 10  Days_Between_Service_and_Claim         10000 non-null  int64
 11  Number_of_Claims_Per_Provider_Monthly  10000 non-null  int64
 12  Provider_Specialty                     9650 non-null   object
 13  Patient_State                          10000 non-null  object
 14  Claim_Status                           10000 non-null  object
 15  Is_Fraud                               10000 non-null  int64
 16  Length_of_Stay                         10000 non-null  int64
 17  Visit_Type                             10000 non-null  object
 18  Chronic_Condition_Flag                 10000 non-null  int64
 19  Prior_Visits_12m                       9650 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(7), object(9)
memory usage: 1.5+ MB

In [8]:
df.describe()

,Patient_Age,Procedure_Code,Claim_Amount,Approved_Amount,Claim_Submission_Date,Days_Between_Service_and_Claim,Number_of_Claims_Per_Provider_Monthly,Is_Fraud,Length_of_Stay,Chronic_Condition_Flag,Prior_Visits_12m
count,10000.000000,10000.00000,10000.000000,10000.000000,10000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,9650.000000
mean,49.755000,86905.21170,572.804406,475.514157,2023-01-10 02:13:12,14.413800,68.628000,0.082900,2.19930,0.292000,3.026425
min,1.000000,36415.00000,60.210000,50.350000,2021-01-06 00:00:00,0.000000,42.000000,0.000000,0.00000,0.000000,0.000000
25%,37.750000,80053.00000,305.205000,257.200000,2022-01-13 00:00:00,7.000000,60.000000,0.000000,1.00000,0.000000,2.000000
50%,50.000000,93000.00000,461.225000,388.370000,2023-01-03 00:00:00,14.000000,66.000000,0.000000,2.00000,0.000000,3.000000
75%,62.000000,99213.00000,711.365000,598.347500,2024-01-05 00:00:00,22.000000,72.000000,0.000000,3.00000,1.000000,4.000000
max,95.000000,99214.00000,6590.700000,4270.890000,2025-01-26 00:00:00,29.000000,144.000000,1.000000,5.00000,1.000000,12.000000
std,17.910144,14965.32496,406.202437,323.257165,NaN,8.489875,14.905872,0.275745,1.71046,0.454705,1.722789

In [9]:
df.duplicated().sum()

0

In [10]:
df.isnull().sum()

Provider_ID                                0
Claim_ID                                   0
Patient_Age                                0
Patient_Gender                             0
Diagnosis_Code                             0
Procedure_Code                             0
Claim_Amount                               0
Approved_Amount                            0
Insurance_Type                           350
Claim_Submission_Date                      0
Days_Between_Service_and_Claim             0
Number_of_Claims_Per_Provider_Monthly      0
Provider_Specialty                       350
Patient_State                              0
Claim_Status                               0
Is_Fraud                                   0
Length_of_Stay                             0
Visit_Type                                 0
Chronic_Condition_Flag                     0
Prior_Visits_12m                         350
dtype: int64

In [11]:
df.nunique()

Provider_ID                                300
Claim_ID                                 10000
Patient_Age                                 95
Patient_Gender                               2
Diagnosis_Code                              10
Procedure_Code                               9
Claim_Amount                              9460
Approved_Amount                           9373
Insurance_Type                               4
Claim_Submission_Date                     1476
Days_Between_Service_and_Claim              30
Number_of_Claims_Per_Provider_Monthly      100
Provider_Specialty                           6
Patient_State                                8
Claim_Status                                 3
Is_Fraud                                     2
Length_of_Stay                               5
Visit_Type                                   3
Chronic_Condition_Flag                       2
Prior_Visits_12m                            13
dtype: int64

# Data cleaning

In [19]:
df['Insurance_Type'] = df['Insurance_Type'].fillna('Unknown')

In [20]:
df['Insurance_Type'].value_counts()

Insurance_Type
Medicare    2425
Medicaid    2419
Private     2405
Self-Pay    2401
Unknown      350
Name: count, dtype: int64

In [21]:
df['Provider_Specialty'] = df['Provider_Specialty'].fillna('Unknown')

In [22]:
df['Provider_Specialty'].value_counts()

Provider_Specialty
Internal Medicine    2019
General Practice     1878
Orthopedics          1616
Neurology            1516
Cardiology           1366
Pulmonology          1255
Unknown               350
Name: count, dtype: int64

In [23]:
df['Prior_Visits_12m'] = df['Prior_Visits_12m'].fillna(0)

In [24]:
df['Prior_Visits_12m'].value_counts()

Prior_Visits_12m
3.0     2177
2.0     2076
4.0     1696
1.0     1436
5.0      999
0.0      810
6.0      487
7.0      214
8.0       74
9.0       20
10.0       7
11.0       3
12.0       1
Name: count, dtype: int64

In [25]:
original = pd.read_excel(r"C:\Users\Robin Sinha\Desktop\BFSI & Healthcare\healthcare_fraud_detection.xlsx")

df['Prior_Visits_12m'] = original['Prior_Visits_12m']

In [26]:
df['Prior_Visits_12m'].isnull().sum()

350

In [27]:
df.duplicated().sum()

0

In [28]:
df.dtypes

Provider_ID                                      object
Claim_ID                                         object
Patient_Age                                       int64
Patient_Gender                                   object
Diagnosis_Code                                   object
Procedure_Code                                    int64
Claim_Amount                                    float64
Approved_Amount                                 float64
Insurance_Type                                   object
Claim_Submission_Date                    datetime64[ns]
Days_Between_Service_and_Claim                    int64
Number_of_Claims_Per_Provider_Monthly             int64
Provider_Specialty                               object
Patient_State                                    object
Claim_Status                                     object
Is_Fraud                                          int64
Length_of_Stay                                    int64
Visit_Type                                       object
Chronic_Condition_Flag                            int64
Prior_Visits_12m                                float64
dtype: object

In [29]:
df['Procedure_Code'] = df['Procedure_Code'].astype(str)

In [30]:
df['Procedure_Code'].dtype

dtype('O')

In [31]:
df['Prior_Visits_12m'].dtype

dtype('float64')

# Data Validation :Categorical

In [35]:
df['Provider_ID'].value_counts(dropna=False)

Provider_ID
P0142    52
P0113    51
P0050    50
P0205    48
P0199    48
         ..
P0053    22
P0193    22
P0213    21
P0159    20
P0134    18
Name: count, Length: 300, dtype: int64

In [36]:
df['Claim_ID'].value_counts(dropna=False)

Claim_ID
C0000000    1
C0006670    1
C0006663    1
C0006664    1
C0006665    1
           ..
C0003333    1
C0003334    1
C0003335    1
C0003336    1
C0009999    1
Name: count, Length: 10000, dtype: int64

In [37]:
df['Patient_Gender'].value_counts(dropna=False)

Patient_Gender
Female    5001
Male      4999
Name: count, dtype: int64

In [38]:
df['Diagnosis_Code'].value_counts(dropna=False)

Diagnosis_Code
M54.5     1055
E78.5     1027
E11.9     1026
I25.10    1025
N39.0     1016
K21.9     1004
F41.9      998
J06.9      955
I10        951
J18.9      943
Name: count, dtype: int64

In [39]:
df['Procedure_Code'].value_counts(dropna=False)

Procedure_Code
99213    2050
97110    1340
87086    1270
93000    1234
71046    1208
85025     937
80053     915
99214     531
36415     515
Name: count, dtype: int64

In [40]:
df['Insurance_Type'].value_counts(dropna=False)

Insurance_Type
Medicare    2425
Medicaid    2419
Private     2405
Self-Pay    2401
Unknown      350
Name: count, dtype: int64

In [41]:
df['Provider_Specialty'].value_counts(dropna=False)

Provider_Specialty
Internal Medicine    2019
General Practice     1878
Orthopedics          1616
Neurology            1516
Cardiology           1366
Pulmonology          1255
Unknown               350
Name: count, dtype: int64

In [42]:
df['Patient_State'].value_counts(dropna=False)

Patient_State
PA    1327
TX    1282
GA    1252
IL    1245
FL    1245
CA    1237
OH    1225
NY    1187
Name: count, dtype: int64

In [43]:
df['Claim_Status'].value_counts(dropna=False)

Claim_Status
Approved    7053
Rejected    1748
Pending     1199
Name: count, dtype: int64

In [44]:
df['Visit_Type'].value_counts(dropna=False)

Visit_Type
Outpatient    3423
Emergency     3368
Inpatient     3209
Name: count, dtype: int64

# Data Validation :Numerical

In [45]:
df['Patient_Age'].describe()

count    10000.000000
mean        49.755000
std         17.910144
min          1.000000
25%         37.750000
50%         50.000000
75%         62.000000
max         95.000000
Name: Patient_Age, dtype: float64

In [46]:
df['Claim_Amount'].describe()

count    10000.000000
mean       572.804406
std        406.202437
min         60.210000
25%        305.205000
50%        461.225000
75%        711.365000
max       6590.700000
Name: Claim_Amount, dtype: float64

In [47]:
df['Approved_Amount'].describe()

count    10000.000000
mean       475.514157
std        323.257165
min         50.350000
25%        257.200000
50%        388.370000
75%        598.347500
max       4270.890000
Name: Approved_Amount, dtype: float64

In [48]:
df['Days_Between_Service_and_Claim'].describe()

count    10000.000000
mean        14.413800
std          8.489875
min          0.000000
25%          7.000000
50%         14.000000
75%         22.000000
max         29.000000
Name: Days_Between_Service_and_Claim, dtype: float64

In [49]:
df['Number_of_Claims_Per_Provider_Monthly'].describe()

count    10000.000000
mean        68.628000
std         14.905872
min         42.000000
25%         60.000000
50%         66.000000
75%         72.000000
max        144.000000
Name: Number_of_Claims_Per_Provider_Monthly, dtype: float64

In [50]:
df['Length_of_Stay'].describe()

count    10000.00000
mean         2.19930
std          1.71046
min          0.00000
25%          1.00000
50%          2.00000
75%          3.00000
max          5.00000
Name: Length_of_Stay, dtype: float64

In [51]:
df['Prior_Visits_12m'].describe()

count    9650.000000
mean        3.026425
std         1.722789
min         0.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        12.000000
Name: Prior_Visits_12m, dtype: float64

In [52]:
df['Is_Fraud'].value_counts()

Is_Fraud
0    9171
1     829
Name: count, dtype: int64

In [53]:
df['Chronic_Condition_Flag'].value_counts()

Chronic_Condition_Flag
0    7080
1    2920
Name: count, dtype: int64

In [54]:
(df['Approved_Amount'] > df['Claim_Amount']).sum()

0

# EDA

Step 1 — Fraud Distribution

In [56]:
df['Is_Fraud'].value_counts()

Is_Fraud
0    9171
1     829
Name: count, dtype: int64

In [57]:
df['Is_Fraud'].value_counts(normalize=True) * 100

Is_Fraud
0    91.71
1     8.29
Name: proportion, dtype: float64

Step 2 — Diagnosis Analysis

In [58]:
df.groupby('Diagnosis_Code')['Is_Fraud'].mean().mul(100).round(2)

Diagnosis_Code
E11.9     6.82
E78.5     8.37
F41.9     6.71
I10       9.15
I25.10    9.95
J06.9     8.17
J18.9     8.38
K21.9     8.37
M54.5     7.87
N39.0     9.15
Name: Is_Fraud, dtype: float64

In [59]:
df.groupby('Diagnosis_Code')['Is_Fraud'].agg(['count', 'sum'])

                count  sum
Diagnosis_Code
E11.9            1026   70
E78.5            1027   86
F41.9             998   67
I10               951   87
I25.10           1025  102
J06.9             955   78
J18.9             943   79
K21.9            1004   84
M54.5            1055   83
N39.0            1016   93

Step 3 — Provider Analysis

In [60]:
df.groupby('Provider_ID')['Is_Fraud'].mean().mul(100).round(2).sort_values(ascending=False)

Provider_ID
P0086    42.11
P0159    35.00
P0110    33.33
P0104    32.35
P0223    31.82
         ...
P0156     0.00
P0233     0.00
P0185     0.00
P0173     0.00
P0059     0.00
Name: Is_Fraud, Length: 300, dtype: float64

In [61]:
df.groupby('Provider_ID')['Is_Fraud'].agg(['count', 'sum']).sort_values('sum', ascending=False).head(10)

             count  sum
Provider_ID
P0086           38   16
P0110           45   15
P0223           44   14
P0104           34   11
P0259           42   10
P0293           33   10
P0027           37   10
P0101           36    9
P0058           37    9
P0255           28    8

In [62]:
df.groupby('Provider_ID')['Claim_Amount'].mean().sort_values(ascending=False).head(10)

Provider_ID
P0101    823.385000
P0223    800.208864
P0289    798.465000
P0110    792.715778
P0078    750.073659
P0248    747.051212
P0182    741.376765
P0178    735.799200
P0074    730.274857
P0082    726.777879
Name: Claim_Amount, dtype: float64

Step 4 — Claim Amount Analysis

In [63]:
df.groupby('Is_Fraud')['Claim_Amount'].mean()

Is_Fraud
0    535.008352
1    990.931797
Name: Claim_Amount, dtype: float64

In [64]:
df.groupby('Is_Fraud').agg(
    Avg_Claim_Amount=('Claim_Amount', 'mean'),
    Avg_Approved_Amount=('Approved_Amount', 'mean')
)

          Avg_Claim_Amount  Avg_Approved_Amount
Is_Fraud
0               535.008352           469.154258
1               990.931797           545.871978

Step 5 — Final Findings

In [66]:
print("Total Claims:", len(df))
print("Fraud-labelled Claims:", (df['Is_Fraud'] == 1).sum())
print("Non-fraud-labelled Claims:", (df['Is_Fraud'] == 0).sum())

Total Claims: 10000
Fraud-labelled Claims: 829
Non-fraud-labelled Claims: 9171